[general]
cpus = 12
editor = "nvim"
doas = true
language = "en-US"
noconfirm = false

[aur]
build = "/home/matt/.cache/aura/builds"
cache = "/home/matt/.cache/aura/cache"
clones = "/home/matt/.cache/aura/packages"
hashes = "/home/matt/.cache/aura/hashes"
chroot = []
ignores = []
git = true
hotedit = false
shellcheck = false
diff = false
delmakedeps = false
clean = false
warn_unknowns = true
nocheck = false
skipdepcheck = false
reverse = true

[backups]
snapshots = "/home/matt/.cache/aura/snapshots"
automatic = true

